<?php
declare(strict_types=1);

namespace App\Constants\Translate;

class MarkRussianConstants
{
  public const MARK_TITLES = [
    'acura' => 'Акура',
    'audi' => 'Ауди',
    'alfa-romeo' => 'Альфа Ромео',
    'bmw' => 'БМВ',
    'byd' => 'БИД',
    'brilliance' => 'Брилианс',
    'cadillac' => 'Кадиллак',
    'changan' => 'Чанган',
    'chery' => 'Чери',
    'chevrolet' => 'Шевроле',
    'chrysler' => 'Крайслер',
    'citroen' => 'Ситроен',
    'daewoo' => 'Дэу',
    'datsun' => 'Датсун',
    'dodge' => 'Додж',
    'dongfeng' => 'Донг фенг',
    'dw-hower' => 'ДВ Ховер',
    'cheryexeed' => 'Иксид',
    'faw' => 'ФАВ',
    'ferrari' => 'Феррари',
    'fiat' => 'Фиат',
    'ford' => 'Форд',
    'foton' => 'Фотон',
    'geely' => 'Джили',
    'genesis' => 'Генезис',
    'great-wall' => 'Грейт Вол',
    'haima' => 'Хайма',
    'hawtai' => 'Хавтай',
    'honda' => 'Хонда',
    'hummer' => 'Хаммер',
    'hyundai' => 'Хендай',
    'infiniti' => 'Инфинити',
    'jac' => 'ЖАК',
    'jaguar' => 'Ягуар',
    'jeep' => 'Джип',
    'isuzu' => 'Исузу',
    'kia' => 'Киа',
    'lada-vaz' => 'Лада',
    'lexus' => 'Лексус',
    'lifan' => 'Лифан',
    'luxgen' => 'Люксген',
    'mazda' => 'Мазда',
    'mg' => 'МГ',
    'mercedes-benz' => 'Мерседес',
    'mini' => 'Мини Купер',
    'land-rover' => 'Ленд Ровер',
    'mitsubishi' => 'Мицубиси',
    'moskvich' => 'Москвич',
    'nissan' => 'Ниссан',
    'opel' => 'Опель',
    'peugeot' => 'Пежо',
    'pontiac' => 'Понтиак',
    'porsche' => 'Порше',
    'ravon' => 'Равон',
    'rover' => 'Ровер',
    'renault' => 'Рено',
    'saab' => 'Сааб',
    'saturn' => 'Сатурн',
    'seat' => 'Сеат',
    'skoda' => 'Шкода',
    'smart' => 'Смарт',
    'ssangyong' => 'Саньенг',
    'subaru' => 'Субару',
    'suzuki' => 'Сузуки',
    'tagaz' => 'Тагаз',
    'toyota' => 'Тойота',
    'uaz' => 'Уаз',
    'volkswagen' => 'Фольксваген',
    'volvo' => 'Вольво',
    'vortex' => 'Вортекс',
    'zotye' => 'Зоти',
    'zaz' => 'Заз'
  ];
}
